# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpER2S6EyTC1zKzX0VXbRH4IGvPk82yQ
"""

import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    BatchNormalization,
    Dropout,
    GlobalAveragePooling2D,
    Dense
)

print("TensorFlow version:", tf.__version__)

X_train = np.load("X_train_mel.npy")
X_val = np.load("X_val_mel.npy")
X_train = X_train / np.max(np.abs(X_train))
X_val = X_val / np.max(np.abs(X_val))
y_train = np.load("y_train.npy")
y_val = np.load("y_val.npy")

print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)

print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)

from google.colab import drive
drive.mount('/content/drive')

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    patience=10,
    restore_best_weights=True
)

model = Sequential([

    # First CNN Block
    Conv2D(32, (3,3), activation='relu', padding='same',
           input_shape=(128,130,1)),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    # Second CNN Block
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    # Third CNN Block
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    # Flatten + Dense
   GlobalAveragePooling2D(),

    Dense(128, activation='relu'),
    Dropout(0.3),

    Dense(8, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop]
)

test_loss, test_acc = model.evaluate(X_val, y_val)

print("Validation Accuracy:", test_acc)

model.save("cnn_block.keras")

print("Model saved successfully!")